/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

// clang-format off
#pragma once

#include <tuple>

#include <executorch/runtime/core/exec_aten/exec_aten.h> // at::Tensor etc.
#include <executorch/codegen/macros.h> // TORCH_API
#include <executorch/runtime/kernel/kernel_runtime_context.h>

// @generated by gen.py from Functions.h

#include "NativeFunctions.h"

namespace torch {
namespace executor {


namespace aten {

// aten::_softmax.out(Tensor self, int dim, bool half_to_float, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & _softmax_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, int64_t dim, bool half_to_float, torch::executor::Tensor & out) {
    return ::torch::executor::native::softmax_out(context, self, dim, half_to_float, out);
}


// aten::add.out(Tensor self, Tensor other, *, Scalar alpha=1, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & add_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, const torch::executor::Tensor & other, const torch::executor::Scalar & alpha, torch::executor::Tensor & out) {
    return ::torch::executor::native::add_out(context, self, other, alpha, out);
}


// aten::cat.out(Tensor[] tensors, int dim=0, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & cat_outf(torch::executor::KernelRuntimeContext & context, torch::executor::TensorList tensors, int64_t dim, torch::executor::Tensor & out) {
    return ::torch::executor::native::cat_out(context, tensors, dim, out);
}


// aten::clone.out(Tensor self, *, MemoryFormat? memory_format=None, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & clone_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, torch::executor::optional<torch::executor::MemoryFormat> memory_format, torch::executor::Tensor & out) {
    return ::torch::executor::native::clone_out(context, self, memory_format, out);
}


// aten::div.out(Tensor self, Tensor other, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & div_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, const torch::executor::Tensor & other, torch::executor::Tensor & out) {
    return ::torch::executor::native::div_out(context, self, other, out);
}


// aten::mean.out(Tensor self, int[1]? dim, bool keepdim=False, *, ScalarType? dtype=None, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & mean_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, torch::executor::optional<torch::executor::ArrayRef<int64_t>> dim, bool keepdim, torch::executor::optional<torch::executor::ScalarType> dtype, torch::executor::Tensor & out) {
    return ::torch::executor::native::mean_dim_out(context, self, dim, keepdim, dtype, out);
}


// aten::mul.out(Tensor self, Tensor other, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & mul_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, const torch::executor::Tensor & other, torch::executor::Tensor & out) {
    return ::torch::executor::native::mul_out(context, self, other, out);
}


// aten::permute_copy.out(Tensor self, int[] dims, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & permute_copy_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, torch::executor::ArrayRef<int64_t> dims, torch::executor::Tensor & out) {
    return ::torch::executor::native::permute_copy_out(context, self, dims, out);
}


// aten::relu.out(Tensor self, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & relu_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, torch::executor::Tensor & out) {
    return ::torch::executor::native::relu_out(context, self, out);
}


// aten::slice_copy.Tensor_out(Tensor self, int dim=0, SymInt? start=None, SymInt? end=None, SymInt step=1, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & slice_copy_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, int64_t dim, torch::executor::optional<int64_t> start, torch::executor::optional<int64_t> end, int64_t step, torch::executor::Tensor & out) {
    return ::torch::executor::native::slice_copy_Tensor_out(context, self, dim, start, end, step, out);
}


// aten::sub.out(Tensor self, Tensor other, *, Scalar alpha=1, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & sub_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, const torch::executor::Tensor & other, const torch::executor::Scalar & alpha, torch::executor::Tensor & out) {
    return ::torch::executor::native::sub_out(context, self, other, alpha, out);
}


// aten::view_copy.out(Tensor self, SymInt[] size, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & view_copy_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, torch::executor::ArrayRef<int64_t> size, torch::executor::Tensor & out) {
    return ::torch::executor::native::view_copy_out(context, self, size, out);
}

} // namespace aten

namespace dim_order_ops {

// dim_order_ops::_to_dim_order_copy.out(Tensor self, *, bool non_blocking=False, int[]? dim_order=None, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & _to_dim_order_copy_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, bool non_blocking, torch::executor::optional<torch::executor::ArrayRef<int64_t>> dim_order, torch::executor::Tensor & out) {
    return ::torch::executor::native::_to_dim_order_copy_out(context, self, non_blocking, dim_order, out);
}


// dim_order_ops::_clone_dim_order.out(Tensor self, *, bool non_blocking=False, int[]? dim_order=None, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & _clone_dim_order_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, bool non_blocking, torch::executor::optional<torch::executor::ArrayRef<int64_t>> dim_order, torch::executor::Tensor & out) {
    return ::torch::executor::native::_clone_dim_order_out(context, self, non_blocking, dim_order, out);
}

} // namespace dim_order_ops

namespace cortex_m {

// cortex_m::quantize_per_tensor.out(Tensor input, float scale, int zero_point, int quant_min, int quant_max, ScalarType dtype, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & quantize_per_tensor_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & input, double scale, int64_t zero_point, int64_t quant_min, int64_t quant_max, torch::executor::ScalarType dtype, torch::executor::Tensor & out) {
    return ::cortex_m::native::quantize_per_tensor_out(context, input, scale, zero_point, quant_min, quant_max, dtype, out);
}


// cortex_m::dequantize_per_tensor.out(Tensor input, float scale, int zero_point, int quant_min, int quant_max, ScalarType dtype, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & dequantize_per_tensor_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & input, double scale, int64_t zero_point, int64_t quant_min, int64_t quant_max, torch::executor::ScalarType dtype, torch::executor::Tensor & out) {
    return ::cortex_m::native::dequantize_per_tensor_out(context, input, scale, zero_point, quant_min, quant_max, dtype, out);
}


// cortex_m::quantized_add.out(Tensor self, int self_zero_point, int self_multiplier, int self_shift, Tensor other, int other_zero_point, int other_multiplier, int other_shift, int output_zero_point, int output_multiplier, int output_shift, int activation_min, int activation_max, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & quantized_add_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, int64_t self_zero_point, int64_t self_multiplier, int64_t self_shift, const torch::executor::Tensor & other, int64_t other_zero_point, int64_t other_multiplier, int64_t other_shift, int64_t output_zero_point, int64_t output_multiplier, int64_t output_shift, int64_t activation_min, int64_t activation_max, torch::executor::Tensor & out) {
    return ::cortex_m::native::quantized_add_out(context, self, self_zero_point, self_multiplier, self_shift, other, other_zero_point, other_multiplier, other_shift, output_zero_point, output_multiplier, output_shift, activation_min, activation_max, out);
}


// cortex_m::quantized_mul.out(Tensor self, int self_zero_point, Tensor other, int other_zero_point, int output_zero_point, int output_multiplier, int output_shift, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & quantized_mul_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, int64_t self_zero_point, const torch::executor::Tensor & other, int64_t other_zero_point, int64_t output_zero_point, int64_t output_multiplier, int64_t output_shift, torch::executor::Tensor & out) {
    return ::cortex_m::native::quantized_mul_out(context, self, self_zero_point, other, other_zero_point, output_zero_point, output_multiplier, output_shift, out);
}


// cortex_m::quantized_div.out(Tensor self, int self_zero_point, Tensor other, int other_zero_point, int output_zero_point, float output_scale, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & quantized_div_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, int64_t self_zero_point, const torch::executor::Tensor & other, int64_t other_zero_point, int64_t output_zero_point, double output_scale, torch::executor::Tensor & out) {
    return ::cortex_m::native::quantized_div_out(context, self, self_zero_point, other, other_zero_point, output_zero_point, output_scale, out);
}


// cortex_m::quantized_activation.out(Tensor input, Tensor lut, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & quantized_activation_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & input, const torch::executor::Tensor & lut, torch::executor::Tensor & out) {
    return ::cortex_m::native::quantized_activation_out(context, input, lut, out);
}


// cortex_m::minimum.out(Tensor self, Tensor other, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & minimum_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, const torch::executor::Tensor & other, torch::executor::Tensor & out) {
    return ::cortex_m::native::minimum_out(context, self, other, out);
}


// cortex_m::maximum.out(Tensor self, Tensor other, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & maximum_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & self, const torch::executor::Tensor & other, torch::executor::Tensor & out) {
    return ::cortex_m::native::maximum_out(context, self, other, out);
}


// cortex_m::quantized_linear.out(Tensor input, Tensor weights, Tensor? bias, Tensor? kernel_sum, int input_offset, int filter_offset, int output_offset, int[] requantize_multipliers, int[] requantize_shifts, int activation_max, int activation_min, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & quantized_linear_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & input, const torch::executor::Tensor & weights, const torch::executor::optional<torch::executor::Tensor> & bias, const torch::executor::optional<torch::executor::Tensor> & kernel_sum, int64_t input_offset, int64_t filter_offset, int64_t output_offset, torch::executor::ArrayRef<int64_t> requantize_multipliers, torch::executor::ArrayRef<int64_t> requantize_shifts, int64_t activation_max, int64_t activation_min, torch::executor::Tensor & out) {
    return ::cortex_m::native::quantized_linear_out(context, input, weights, bias, kernel_sum, input_offset, filter_offset, output_offset, requantize_multipliers, requantize_shifts, activation_max, activation_min, out);
}


// cortex_m::softmax.out(Tensor input, int dim, int input_zero_point, int output_zero_point, int input_multiplier, int input_shift, int diff_min, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & softmax_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & input, int64_t dim, int64_t input_zero_point, int64_t output_zero_point, int64_t input_multiplier, int64_t input_shift, int64_t diff_min, torch::executor::Tensor & out) {
    return ::cortex_m::native::softmax_out(context, input, dim, input_zero_point, output_zero_point, input_multiplier, input_shift, diff_min, out);
}


// cortex_m::transpose.out(Tensor input, int[] perm, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & transpose_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & input, torch::executor::ArrayRef<int64_t> perm, torch::executor::Tensor & out) {
    return ::cortex_m::native::transpose_out(context, input, perm, out);
}


// cortex_m::pad.out(Tensor input, int[] pre_pad, int[] post_pad, int pad_value, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & pad_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & input, torch::executor::ArrayRef<int64_t> pre_pad, torch::executor::ArrayRef<int64_t> post_pad, int64_t pad_value, torch::executor::Tensor & out) {
    return ::cortex_m::native::pad_out(context, input, pre_pad, post_pad, pad_value, out);
}


// cortex_m::quantized_conv2d.out(Tensor input, Tensor weight, Tensor? bias, int[] stride, int[] padding, int[] dilation, int input_offset, int output_offset, Tensor requantize_multipliers, Tensor requantize_shifts, int activation_min, int activation_max, Tensor scratch, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & quantized_conv2d_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & input, const torch::executor::Tensor & weight, const torch::executor::optional<torch::executor::Tensor> & bias, torch::executor::ArrayRef<int64_t> stride, torch::executor::ArrayRef<int64_t> padding, torch::executor::ArrayRef<int64_t> dilation, int64_t input_offset, int64_t output_offset, const torch::executor::Tensor & requantize_multipliers, const torch::executor::Tensor & requantize_shifts, int64_t activation_min, int64_t activation_max, const torch::executor::Tensor & scratch, torch::executor::Tensor & out) {
    return ::cortex_m::native::quantized_conv2d_out(context, input, weight, bias, stride, padding, dilation, input_offset, output_offset, requantize_multipliers, requantize_shifts, activation_min, activation_max, scratch, out);
}


// cortex_m::quantized_depthwise_conv2d.out(Tensor input, Tensor weight, Tensor? bias, int[] stride, int[] padding, int[] dilation, int depth_multiplier, int input_offset, int output_offset, Tensor requantize_multipliers, Tensor requantize_shifts, int activation_min, int activation_max, Tensor scratch, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & quantized_depthwise_conv2d_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & input, const torch::executor::Tensor & weight, const torch::executor::optional<torch::executor::Tensor> & bias, torch::executor::ArrayRef<int64_t> stride, torch::executor::ArrayRef<int64_t> padding, torch::executor::ArrayRef<int64_t> dilation, int64_t depth_multiplier, int64_t input_offset, int64_t output_offset, const torch::executor::Tensor & requantize_multipliers, const torch::executor::Tensor & requantize_shifts, int64_t activation_min, int64_t activation_max, const torch::executor::Tensor & scratch, torch::executor::Tensor & out) {
    return ::cortex_m::native::quantized_depthwise_conv2d_out(context, input, weight, bias, stride, padding, dilation, depth_multiplier, input_offset, output_offset, requantize_multipliers, requantize_shifts, activation_min, activation_max, scratch, out);
}


// cortex_m::quantized_transpose_conv2d.out(Tensor input, Tensor weight, Tensor? bias, int[] stride, int[] padding, int[] output_padding, int[] dilation, int input_offset, int output_offset, Tensor requantize_multipliers, Tensor requantize_shifts, int activation_min, int activation_max, Tensor scratch, Tensor output_scratch, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & quantized_transpose_conv2d_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & input, const torch::executor::Tensor & weight, const torch::executor::optional<torch::executor::Tensor> & bias, torch::executor::ArrayRef<int64_t> stride, torch::executor::ArrayRef<int64_t> padding, torch::executor::ArrayRef<int64_t> output_padding, torch::executor::ArrayRef<int64_t> dilation, int64_t input_offset, int64_t output_offset, const torch::executor::Tensor & requantize_multipliers, const torch::executor::Tensor & requantize_shifts, int64_t activation_min, int64_t activation_max, const torch::executor::Tensor & scratch, const torch::executor::Tensor & output_scratch, torch::executor::Tensor & out) {
    return ::cortex_m::native::quantized_transpose_conv2d_out(context, input, weight, bias, stride, padding, output_padding, dilation, input_offset, output_offset, requantize_multipliers, requantize_shifts, activation_min, activation_max, scratch, output_scratch, out);
}


// cortex_m::quantized_avg_pool2d.out(Tensor input, int[] kernel_size, int[] stride, int[] padding, bool ceil_mode, int zero_point, int multiplier, int shift, Tensor scratch, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & quantized_avg_pool2d_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & input, torch::executor::ArrayRef<int64_t> kernel_size, torch::executor::ArrayRef<int64_t> stride, torch::executor::ArrayRef<int64_t> padding, bool ceil_mode, int64_t zero_point, int64_t multiplier, int64_t shift, const torch::executor::Tensor & scratch, torch::executor::Tensor & out) {
    return ::cortex_m::native::quantized_avg_pool2d_out(context, input, kernel_size, stride, padding, ceil_mode, zero_point, multiplier, shift, scratch, out);
}


// cortex_m::quantized_max_pool2d.out(Tensor input, int[] kernel_size, int[] stride, int[] padding, int[] dilation, bool ceil_mode, int input_zero_point, int output_zero_point, int activation_min, int activation_max, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & quantized_max_pool2d_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & input, torch::executor::ArrayRef<int64_t> kernel_size, torch::executor::ArrayRef<int64_t> stride, torch::executor::ArrayRef<int64_t> padding, torch::executor::ArrayRef<int64_t> dilation, bool ceil_mode, int64_t input_zero_point, int64_t output_zero_point, int64_t activation_min, int64_t activation_max, torch::executor::Tensor & out) {
    return ::cortex_m::native::quantized_max_pool2d_out(context, input, kernel_size, stride, padding, dilation, ceil_mode, input_zero_point, output_zero_point, activation_min, activation_max, out);
}


// cortex_m::quantized_batch_matmul.out(Tensor lhs, int lhs_zero_point, Tensor rhs_transposed, int rhs_zero_point, int output_zero_point, int output_multiplier, int output_shift, Tensor scratch, *, Tensor(a!) out) -> Tensor(a!)
TORCH_API inline torch::executor::Tensor & quantized_batch_matmul_outf(torch::executor::KernelRuntimeContext & context, const torch::executor::Tensor & lhs, int64_t lhs_zero_point, const torch::executor::Tensor & rhs_transposed, int64_t rhs_zero_point, int64_t output_zero_point, int64_t output_multiplier, int64_t output_shift, const torch::executor::Tensor & scratch, torch::executor::Tensor & out) {
    return ::cortex_m::native::quantized_batch_matmul_out(context, lhs, lhs_zero_point, rhs_transposed, rhs_zero_point, output_zero_point, output_multiplier, output_shift, scratch, out);
}

} // namespace cortex_m

} // namespace executor
} // namespace torch
