/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

#include <executorch/runtime/core/evalue.h>
#include <executorch/runtime/core/exec_aten/exec_aten.h>
#include <executorch/runtime/core/exec_aten/util/tensor_util.h>
#include <executorch/runtime/core/span.h>
#include <executorch/runtime/kernel/operator_registry.h>
#include <executorch/runtime/platform/profiler.h>
#include "NativeFunctions.h" // Generated Function import headers
// @generated by gen.py from RegisterCodegenUnboxedKernels.cpp

// NOTE [Sharded File]: This file is generated in a sharded fashion to speed up
// incremental rebuilds. See the comment at the top of
// templates/VariableType.cpp for an analogous, in-depth discussion.
//
// Generated by tools/jit/gen_unboxing.py. This file registers all ATen ops into
// JIT op registry instead of c10 dispatcher. JIT op registry only takes boxed
// kernels, so we are calling unboxing functions in UnboxingFunctions.h to cast
// arguments into C++ types (instead of IValue) and delegate to unboxed kernels.
using KernelSpan = ::executorch::runtime::Span<
    const ::executorch::ET_RUNTIME_NAMESPACE::Kernel>;
namespace torch {
namespace executor {
namespace function {
namespace {

static Kernel kernels_to_register[] = {

    Kernel(
        "aten::_softmax.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 5, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)5, stack.size());
            EValue& self = *stack[0];
    	EValue& dim = *stack[1];
    	EValue& half_to_float = *stack[2];
    	EValue& out = *stack[3];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();
    	int64_t dim_base = dim.to<int64_t>();
    	bool half_to_float_base = half_to_float.to<bool>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call__softmax.out");
            EXECUTORCH_SCOPE_PROF("native_call__softmax.out");
            torch::executor::native::softmax_out(context, self_base, dim_base, half_to_float_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[3]);


        }
    ),

    Kernel(
        "aten::add.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 5, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)5, stack.size());
            EValue& self = *stack[0];
    	EValue& other = *stack[1];
    	EValue& alpha = *stack[2];
    	EValue& out = *stack[3];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();
    	const torch::executor::Tensor & other_base = other.to<torch::executor::Tensor>();
    	const torch::executor::Scalar & alpha_base = alpha.to<torch::executor::Scalar>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_add.out");
            EXECUTORCH_SCOPE_PROF("native_call_add.out");
            torch::executor::native::add_out(context, self_base, other_base, alpha_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[3]);


        }
    ),

    Kernel(
        "aten::cat.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 4, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)4, stack.size());
            EValue& tensors = *stack[0];
    	EValue& dim = *stack[1];
    	EValue& out = *stack[2];

    	    auto tensors_list_out = tensors.toTensorList();

    	int64_t dim_base = dim.to<int64_t>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_cat.out");
            EXECUTORCH_SCOPE_PROF("native_call_cat.out");
            torch::executor::native::cat_out(context, tensors_list_out, dim_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[2]);


        }
    ),

    Kernel(
        "aten::clone.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 4, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)4, stack.size());
            EValue& self = *stack[0];
    	EValue& memory_format = *stack[1];
    	EValue& out = *stack[2];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();

    	    auto memory_format_opt_out = memory_format.toOptional<torch::executor::MemoryFormat>();

    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_clone.out");
            EXECUTORCH_SCOPE_PROF("native_call_clone.out");
            torch::executor::native::clone_out(context, self_base, memory_format_opt_out, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[2]);


        }
    ),

    Kernel(
        "aten::div.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 4, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)4, stack.size());
            EValue& self = *stack[0];
    	EValue& other = *stack[1];
    	EValue& out = *stack[2];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();
    	const torch::executor::Tensor & other_base = other.to<torch::executor::Tensor>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_div.out");
            EXECUTORCH_SCOPE_PROF("native_call_div.out");
            torch::executor::native::div_out(context, self_base, other_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[2]);


        }
    ),

    Kernel(
        "aten::mean.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 6, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)6, stack.size());
            EValue& self = *stack[0];
    	EValue& dim = *stack[1];
    	EValue& keepdim = *stack[2];
    	EValue& dtype = *stack[3];
    	EValue& out = *stack[4];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();

    	    auto dim_opt_out = dim.toOptional<torch::executor::ArrayRef<int64_t>>();

    	bool keepdim_base = keepdim.to<bool>();

    	    auto dtype_opt_out = dtype.toOptional<torch::executor::ScalarType>();

    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_mean.out");
            EXECUTORCH_SCOPE_PROF("native_call_mean.out");
            torch::executor::native::mean_dim_out(context, self_base, dim_opt_out, keepdim_base, dtype_opt_out, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[4]);


        }
    ),

    Kernel(
        "aten::mul.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 4, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)4, stack.size());
            EValue& self = *stack[0];
    	EValue& other = *stack[1];
    	EValue& out = *stack[2];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();
    	const torch::executor::Tensor & other_base = other.to<torch::executor::Tensor>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_mul.out");
            EXECUTORCH_SCOPE_PROF("native_call_mul.out");
            torch::executor::native::mul_out(context, self_base, other_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[2]);


        }
    ),

    Kernel(
        "aten::permute_copy.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 4, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)4, stack.size());
            EValue& self = *stack[0];
    	EValue& dims = *stack[1];
    	EValue& out = *stack[2];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();

    	    auto dims_list_out = dims.toIntList();

    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_permute_copy.out");
            EXECUTORCH_SCOPE_PROF("native_call_permute_copy.out");
            torch::executor::native::permute_copy_out(context, self_base, dims_list_out, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[2]);


        }
    ),

    Kernel(
        "aten::relu.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 3, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)3, stack.size());
            EValue& self = *stack[0];
    	EValue& out = *stack[1];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_relu.out");
            EXECUTORCH_SCOPE_PROF("native_call_relu.out");
            torch::executor::native::relu_out(context, self_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[1]);


        }
    ),

    Kernel(
        "aten::slice_copy.Tensor_out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 7, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)7, stack.size());
            EValue& self = *stack[0];
    	EValue& dim = *stack[1];
    	EValue& start = *stack[2];
    	EValue& end = *stack[3];
    	EValue& step = *stack[4];
    	EValue& out = *stack[5];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();
    	int64_t dim_base = dim.to<int64_t>();

    	    auto start_opt_out = start.toOptional<int64_t>();


    	    auto end_opt_out = end.toOptional<int64_t>();

    	int64_t step_base = step.to<int64_t>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_slice_copy.Tensor_out");
            EXECUTORCH_SCOPE_PROF("native_call_slice_copy.Tensor_out");
            torch::executor::native::slice_copy_Tensor_out(context, self_base, dim_base, start_opt_out, end_opt_out, step_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[5]);


        }
    ),

    Kernel(
        "aten::sub.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 5, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)5, stack.size());
            EValue& self = *stack[0];
    	EValue& other = *stack[1];
    	EValue& alpha = *stack[2];
    	EValue& out = *stack[3];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();
    	const torch::executor::Tensor & other_base = other.to<torch::executor::Tensor>();
    	const torch::executor::Scalar & alpha_base = alpha.to<torch::executor::Scalar>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_sub.out");
            EXECUTORCH_SCOPE_PROF("native_call_sub.out");
            torch::executor::native::sub_out(context, self_base, other_base, alpha_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[3]);


        }
    ),

    Kernel(
        "aten::view_copy.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 4, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)4, stack.size());
            EValue& self = *stack[0];
    	EValue& size = *stack[1];
    	EValue& out = *stack[2];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();

    	    auto size_list_out = size.toIntList();

    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_view_copy.out");
            EXECUTORCH_SCOPE_PROF("native_call_view_copy.out");
            torch::executor::native::view_copy_out(context, self_base, size_list_out, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[2]);


        }
    ),

    Kernel(
        "dim_order_ops::_to_dim_order_copy.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 5, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)5, stack.size());
            EValue& self = *stack[0];
    	EValue& non_blocking = *stack[1];
    	EValue& dim_order = *stack[2];
    	EValue& out = *stack[3];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();
    	bool non_blocking_base = non_blocking.to<bool>();

    	    auto dim_order_opt_out = dim_order.toOptional<torch::executor::ArrayRef<int64_t>>();

    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call__to_dim_order_copy.out");
            EXECUTORCH_SCOPE_PROF("native_call__to_dim_order_copy.out");
            torch::executor::native::_to_dim_order_copy_out(context, self_base, non_blocking_base, dim_order_opt_out, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[3]);


        }
    ),

    Kernel(
        "dim_order_ops::_clone_dim_order.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 5, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)5, stack.size());
            EValue& self = *stack[0];
    	EValue& non_blocking = *stack[1];
    	EValue& dim_order = *stack[2];
    	EValue& out = *stack[3];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();
    	bool non_blocking_base = non_blocking.to<bool>();

    	    auto dim_order_opt_out = dim_order.toOptional<torch::executor::ArrayRef<int64_t>>();

    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call__clone_dim_order.out");
            EXECUTORCH_SCOPE_PROF("native_call__clone_dim_order.out");
            torch::executor::native::_clone_dim_order_out(context, self_base, non_blocking_base, dim_order_opt_out, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[3]);


        }
    ),

    Kernel(
        "cortex_m::quantize_per_tensor.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 8, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)8, stack.size());
            EValue& input = *stack[0];
    	EValue& scale = *stack[1];
    	EValue& zero_point = *stack[2];
    	EValue& quant_min = *stack[3];
    	EValue& quant_max = *stack[4];
    	EValue& dtype = *stack[5];
    	EValue& out = *stack[6];
    	const torch::executor::Tensor & input_base = input.to<torch::executor::Tensor>();
    	double scale_base = scale.to<double>();
    	int64_t zero_point_base = zero_point.to<int64_t>();
    	int64_t quant_min_base = quant_min.to<int64_t>();
    	int64_t quant_max_base = quant_max.to<int64_t>();
    	torch::executor::ScalarType dtype_base = dtype.to<torch::executor::ScalarType>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_quantize_per_tensor.out");
            EXECUTORCH_SCOPE_PROF("native_call_quantize_per_tensor.out");
            cortex_m::native::quantize_per_tensor_out(context, input_base, scale_base, zero_point_base, quant_min_base, quant_max_base, dtype_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[6]);


        }
    ),

    Kernel(
        "cortex_m::dequantize_per_tensor.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 8, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)8, stack.size());
            EValue& input = *stack[0];
    	EValue& scale = *stack[1];
    	EValue& zero_point = *stack[2];
    	EValue& quant_min = *stack[3];
    	EValue& quant_max = *stack[4];
    	EValue& dtype = *stack[5];
    	EValue& out = *stack[6];
    	const torch::executor::Tensor & input_base = input.to<torch::executor::Tensor>();
    	double scale_base = scale.to<double>();
    	int64_t zero_point_base = zero_point.to<int64_t>();
    	int64_t quant_min_base = quant_min.to<int64_t>();
    	int64_t quant_max_base = quant_max.to<int64_t>();
    	torch::executor::ScalarType dtype_base = dtype.to<torch::executor::ScalarType>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_dequantize_per_tensor.out");
            EXECUTORCH_SCOPE_PROF("native_call_dequantize_per_tensor.out");
            cortex_m::native::dequantize_per_tensor_out(context, input_base, scale_base, zero_point_base, quant_min_base, quant_max_base, dtype_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[6]);


        }
    ),

    Kernel(
        "cortex_m::quantized_add.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 15, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)15, stack.size());
            EValue& self = *stack[0];
    	EValue& self_zero_point = *stack[1];
    	EValue& self_multiplier = *stack[2];
    	EValue& self_shift = *stack[3];
    	EValue& other = *stack[4];
    	EValue& other_zero_point = *stack[5];
    	EValue& other_multiplier = *stack[6];
    	EValue& other_shift = *stack[7];
    	EValue& output_zero_point = *stack[8];
    	EValue& output_multiplier = *stack[9];
    	EValue& output_shift = *stack[10];
    	EValue& activation_min = *stack[11];
    	EValue& activation_max = *stack[12];
    	EValue& out = *stack[13];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();
    	int64_t self_zero_point_base = self_zero_point.to<int64_t>();
    	int64_t self_multiplier_base = self_multiplier.to<int64_t>();
    	int64_t self_shift_base = self_shift.to<int64_t>();
    	const torch::executor::Tensor & other_base = other.to<torch::executor::Tensor>();
    	int64_t other_zero_point_base = other_zero_point.to<int64_t>();
    	int64_t other_multiplier_base = other_multiplier.to<int64_t>();
    	int64_t other_shift_base = other_shift.to<int64_t>();
    	int64_t output_zero_point_base = output_zero_point.to<int64_t>();
    	int64_t output_multiplier_base = output_multiplier.to<int64_t>();
    	int64_t output_shift_base = output_shift.to<int64_t>();
    	int64_t activation_min_base = activation_min.to<int64_t>();
    	int64_t activation_max_base = activation_max.to<int64_t>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_quantized_add.out");
            EXECUTORCH_SCOPE_PROF("native_call_quantized_add.out");
            cortex_m::native::quantized_add_out(context, self_base, self_zero_point_base, self_multiplier_base, self_shift_base, other_base, other_zero_point_base, other_multiplier_base, other_shift_base, output_zero_point_base, output_multiplier_base, output_shift_base, activation_min_base, activation_max_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[13]);


        }
    ),

    Kernel(
        "cortex_m::quantized_mul.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 9, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)9, stack.size());
            EValue& self = *stack[0];
    	EValue& self_zero_point = *stack[1];
    	EValue& other = *stack[2];
    	EValue& other_zero_point = *stack[3];
    	EValue& output_zero_point = *stack[4];
    	EValue& output_multiplier = *stack[5];
    	EValue& output_shift = *stack[6];
    	EValue& out = *stack[7];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();
    	int64_t self_zero_point_base = self_zero_point.to<int64_t>();
    	const torch::executor::Tensor & other_base = other.to<torch::executor::Tensor>();
    	int64_t other_zero_point_base = other_zero_point.to<int64_t>();
    	int64_t output_zero_point_base = output_zero_point.to<int64_t>();
    	int64_t output_multiplier_base = output_multiplier.to<int64_t>();
    	int64_t output_shift_base = output_shift.to<int64_t>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_quantized_mul.out");
            EXECUTORCH_SCOPE_PROF("native_call_quantized_mul.out");
            cortex_m::native::quantized_mul_out(context, self_base, self_zero_point_base, other_base, other_zero_point_base, output_zero_point_base, output_multiplier_base, output_shift_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[7]);


        }
    ),

    Kernel(
        "cortex_m::quantized_div.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 8, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)8, stack.size());
            EValue& self = *stack[0];
    	EValue& self_zero_point = *stack[1];
    	EValue& other = *stack[2];
    	EValue& other_zero_point = *stack[3];
    	EValue& output_zero_point = *stack[4];
    	EValue& output_scale = *stack[5];
    	EValue& out = *stack[6];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();
    	int64_t self_zero_point_base = self_zero_point.to<int64_t>();
    	const torch::executor::Tensor & other_base = other.to<torch::executor::Tensor>();
    	int64_t other_zero_point_base = other_zero_point.to<int64_t>();
    	int64_t output_zero_point_base = output_zero_point.to<int64_t>();
    	double output_scale_base = output_scale.to<double>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_quantized_div.out");
            EXECUTORCH_SCOPE_PROF("native_call_quantized_div.out");
            cortex_m::native::quantized_div_out(context, self_base, self_zero_point_base, other_base, other_zero_point_base, output_zero_point_base, output_scale_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[6]);


        }
    ),

    Kernel(
        "cortex_m::quantized_activation.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 4, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)4, stack.size());
            EValue& input = *stack[0];
    	EValue& lut = *stack[1];
    	EValue& out = *stack[2];
    	const torch::executor::Tensor & input_base = input.to<torch::executor::Tensor>();
    	const torch::executor::Tensor & lut_base = lut.to<torch::executor::Tensor>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_quantized_activation.out");
            EXECUTORCH_SCOPE_PROF("native_call_quantized_activation.out");
            cortex_m::native::quantized_activation_out(context, input_base, lut_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[2]);


        }
    ),

    Kernel(
        "cortex_m::minimum.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 4, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)4, stack.size());
            EValue& self = *stack[0];
    	EValue& other = *stack[1];
    	EValue& out = *stack[2];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();
    	const torch::executor::Tensor & other_base = other.to<torch::executor::Tensor>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_minimum.out");
            EXECUTORCH_SCOPE_PROF("native_call_minimum.out");
            cortex_m::native::minimum_out(context, self_base, other_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[2]);


        }
    ),

    Kernel(
        "cortex_m::maximum.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 4, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)4, stack.size());
            EValue& self = *stack[0];
    	EValue& other = *stack[1];
    	EValue& out = *stack[2];
    	const torch::executor::Tensor & self_base = self.to<torch::executor::Tensor>();
    	const torch::executor::Tensor & other_base = other.to<torch::executor::Tensor>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_maximum.out");
            EXECUTORCH_SCOPE_PROF("native_call_maximum.out");
            cortex_m::native::maximum_out(context, self_base, other_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[2]);


        }
    ),

    Kernel(
        "cortex_m::quantized_linear.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 13, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)13, stack.size());
            EValue& input = *stack[0];
    	EValue& weights = *stack[1];
    	EValue& bias = *stack[2];
    	EValue& kernel_sum = *stack[3];
    	EValue& input_offset = *stack[4];
    	EValue& filter_offset = *stack[5];
    	EValue& output_offset = *stack[6];
    	EValue& requantize_multipliers = *stack[7];
    	EValue& requantize_shifts = *stack[8];
    	EValue& activation_max = *stack[9];
    	EValue& activation_min = *stack[10];
    	EValue& out = *stack[11];
    	const torch::executor::Tensor & input_base = input.to<torch::executor::Tensor>();
    	const torch::executor::Tensor & weights_base = weights.to<torch::executor::Tensor>();

    	    auto bias_opt_out = bias.toOptional<torch::executor::Tensor>();


    	    auto kernel_sum_opt_out = kernel_sum.toOptional<torch::executor::Tensor>();

    	int64_t input_offset_base = input_offset.to<int64_t>();
    	int64_t filter_offset_base = filter_offset.to<int64_t>();
    	int64_t output_offset_base = output_offset.to<int64_t>();

    	    auto requantize_multipliers_list_out = requantize_multipliers.toIntList();


    	    auto requantize_shifts_list_out = requantize_shifts.toIntList();

    	int64_t activation_max_base = activation_max.to<int64_t>();
    	int64_t activation_min_base = activation_min.to<int64_t>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_quantized_linear.out");
            EXECUTORCH_SCOPE_PROF("native_call_quantized_linear.out");
            cortex_m::native::quantized_linear_out(context, input_base, weights_base, bias_opt_out, kernel_sum_opt_out, input_offset_base, filter_offset_base, output_offset_base, requantize_multipliers_list_out, requantize_shifts_list_out, activation_max_base, activation_min_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[11]);


        }
    ),

    Kernel(
        "cortex_m::softmax.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 9, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)9, stack.size());
            EValue& input = *stack[0];
    	EValue& dim = *stack[1];
    	EValue& input_zero_point = *stack[2];
    	EValue& output_zero_point = *stack[3];
    	EValue& input_multiplier = *stack[4];
    	EValue& input_shift = *stack[5];
    	EValue& diff_min = *stack[6];
    	EValue& out = *stack[7];
    	const torch::executor::Tensor & input_base = input.to<torch::executor::Tensor>();
    	int64_t dim_base = dim.to<int64_t>();
    	int64_t input_zero_point_base = input_zero_point.to<int64_t>();
    	int64_t output_zero_point_base = output_zero_point.to<int64_t>();
    	int64_t input_multiplier_base = input_multiplier.to<int64_t>();
    	int64_t input_shift_base = input_shift.to<int64_t>();
    	int64_t diff_min_base = diff_min.to<int64_t>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_softmax.out");
            EXECUTORCH_SCOPE_PROF("native_call_softmax.out");
            cortex_m::native::softmax_out(context, input_base, dim_base, input_zero_point_base, output_zero_point_base, input_multiplier_base, input_shift_base, diff_min_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[7]);


        }
    ),

    Kernel(
        "cortex_m::transpose.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 4, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)4, stack.size());
            EValue& input = *stack[0];
    	EValue& perm = *stack[1];
    	EValue& out = *stack[2];
    	const torch::executor::Tensor & input_base = input.to<torch::executor::Tensor>();

    	    auto perm_list_out = perm.toIntList();

    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_transpose.out");
            EXECUTORCH_SCOPE_PROF("native_call_transpose.out");
            cortex_m::native::transpose_out(context, input_base, perm_list_out, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[2]);


        }
    ),

    Kernel(
        "cortex_m::pad.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 6, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)6, stack.size());
            EValue& input = *stack[0];
    	EValue& pre_pad = *stack[1];
    	EValue& post_pad = *stack[2];
    	EValue& pad_value = *stack[3];
    	EValue& out = *stack[4];
    	const torch::executor::Tensor & input_base = input.to<torch::executor::Tensor>();

    	    auto pre_pad_list_out = pre_pad.toIntList();


    	    auto post_pad_list_out = post_pad.toIntList();

    	int64_t pad_value_base = pad_value.to<int64_t>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_pad.out");
            EXECUTORCH_SCOPE_PROF("native_call_pad.out");
            cortex_m::native::pad_out(context, input_base, pre_pad_list_out, post_pad_list_out, pad_value_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[4]);


        }
    ),

    Kernel(
        "cortex_m::quantized_conv2d.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 15, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)15, stack.size());
            EValue& input = *stack[0];
    	EValue& weight = *stack[1];
    	EValue& bias = *stack[2];
    	EValue& stride = *stack[3];
    	EValue& padding = *stack[4];
    	EValue& dilation = *stack[5];
    	EValue& input_offset = *stack[6];
    	EValue& output_offset = *stack[7];
    	EValue& requantize_multipliers = *stack[8];
    	EValue& requantize_shifts = *stack[9];
    	EValue& activation_min = *stack[10];
    	EValue& activation_max = *stack[11];
    	EValue& scratch = *stack[12];
    	EValue& out = *stack[13];
    	const torch::executor::Tensor & input_base = input.to<torch::executor::Tensor>();
    	const torch::executor::Tensor & weight_base = weight.to<torch::executor::Tensor>();

    	    auto bias_opt_out = bias.toOptional<torch::executor::Tensor>();


    	    auto stride_list_out = stride.toIntList();


    	    auto padding_list_out = padding.toIntList();


    	    auto dilation_list_out = dilation.toIntList();

    	int64_t input_offset_base = input_offset.to<int64_t>();
    	int64_t output_offset_base = output_offset.to<int64_t>();
    	const torch::executor::Tensor & requantize_multipliers_base = requantize_multipliers.to<torch::executor::Tensor>();
    	const torch::executor::Tensor & requantize_shifts_base = requantize_shifts.to<torch::executor::Tensor>();
    	int64_t activation_min_base = activation_min.to<int64_t>();
    	int64_t activation_max_base = activation_max.to<int64_t>();
    	const torch::executor::Tensor & scratch_base = scratch.to<torch::executor::Tensor>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_quantized_conv2d.out");
            EXECUTORCH_SCOPE_PROF("native_call_quantized_conv2d.out");
            cortex_m::native::quantized_conv2d_out(context, input_base, weight_base, bias_opt_out, stride_list_out, padding_list_out, dilation_list_out, input_offset_base, output_offset_base, requantize_multipliers_base, requantize_shifts_base, activation_min_base, activation_max_base, scratch_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[13]);


        }
    ),

    Kernel(
        "cortex_m::quantized_depthwise_conv2d.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 16, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)16, stack.size());
            EValue& input = *stack[0];
    	EValue& weight = *stack[1];
    	EValue& bias = *stack[2];
    	EValue& stride = *stack[3];
    	EValue& padding = *stack[4];
    	EValue& dilation = *stack[5];
    	EValue& depth_multiplier = *stack[6];
    	EValue& input_offset = *stack[7];
    	EValue& output_offset = *stack[8];
    	EValue& requantize_multipliers = *stack[9];
    	EValue& requantize_shifts = *stack[10];
    	EValue& activation_min = *stack[11];
    	EValue& activation_max = *stack[12];
    	EValue& scratch = *stack[13];
    	EValue& out = *stack[14];
    	const torch::executor::Tensor & input_base = input.to<torch::executor::Tensor>();
    	const torch::executor::Tensor & weight_base = weight.to<torch::executor::Tensor>();

    	    auto bias_opt_out = bias.toOptional<torch::executor::Tensor>();


    	    auto stride_list_out = stride.toIntList();


    	    auto padding_list_out = padding.toIntList();


    	    auto dilation_list_out = dilation.toIntList();

    	int64_t depth_multiplier_base = depth_multiplier.to<int64_t>();
    	int64_t input_offset_base = input_offset.to<int64_t>();
    	int64_t output_offset_base = output_offset.to<int64_t>();
    	const torch::executor::Tensor & requantize_multipliers_base = requantize_multipliers.to<torch::executor::Tensor>();
    	const torch::executor::Tensor & requantize_shifts_base = requantize_shifts.to<torch::executor::Tensor>();
    	int64_t activation_min_base = activation_min.to<int64_t>();
    	int64_t activation_max_base = activation_max.to<int64_t>();
    	const torch::executor::Tensor & scratch_base = scratch.to<torch::executor::Tensor>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_quantized_depthwise_conv2d.out");
            EXECUTORCH_SCOPE_PROF("native_call_quantized_depthwise_conv2d.out");
            cortex_m::native::quantized_depthwise_conv2d_out(context, input_base, weight_base, bias_opt_out, stride_list_out, padding_list_out, dilation_list_out, depth_multiplier_base, input_offset_base, output_offset_base, requantize_multipliers_base, requantize_shifts_base, activation_min_base, activation_max_base, scratch_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[14]);


        }
    ),

    Kernel(
        "cortex_m::quantized_transpose_conv2d.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 17, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)17, stack.size());
            EValue& input = *stack[0];
    	EValue& weight = *stack[1];
    	EValue& bias = *stack[2];
    	EValue& stride = *stack[3];
    	EValue& padding = *stack[4];
    	EValue& output_padding = *stack[5];
    	EValue& dilation = *stack[6];
    	EValue& input_offset = *stack[7];
    	EValue& output_offset = *stack[8];
    	EValue& requantize_multipliers = *stack[9];
    	EValue& requantize_shifts = *stack[10];
    	EValue& activation_min = *stack[11];
    	EValue& activation_max = *stack[12];
    	EValue& scratch = *stack[13];
    	EValue& output_scratch = *stack[14];
    	EValue& out = *stack[15];
    	const torch::executor::Tensor & input_base = input.to<torch::executor::Tensor>();
    	const torch::executor::Tensor & weight_base = weight.to<torch::executor::Tensor>();

    	    auto bias_opt_out = bias.toOptional<torch::executor::Tensor>();


    	    auto stride_list_out = stride.toIntList();


    	    auto padding_list_out = padding.toIntList();


    	    auto output_padding_list_out = output_padding.toIntList();


    	    auto dilation_list_out = dilation.toIntList();

    	int64_t input_offset_base = input_offset.to<int64_t>();
    	int64_t output_offset_base = output_offset.to<int64_t>();
    	const torch::executor::Tensor & requantize_multipliers_base = requantize_multipliers.to<torch::executor::Tensor>();
    	const torch::executor::Tensor & requantize_shifts_base = requantize_shifts.to<torch::executor::Tensor>();
    	int64_t activation_min_base = activation_min.to<int64_t>();
    	int64_t activation_max_base = activation_max.to<int64_t>();
    	const torch::executor::Tensor & scratch_base = scratch.to<torch::executor::Tensor>();
    	const torch::executor::Tensor & output_scratch_base = output_scratch.to<torch::executor::Tensor>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_quantized_transpose_conv2d.out");
            EXECUTORCH_SCOPE_PROF("native_call_quantized_transpose_conv2d.out");
            cortex_m::native::quantized_transpose_conv2d_out(context, input_base, weight_base, bias_opt_out, stride_list_out, padding_list_out, output_padding_list_out, dilation_list_out, input_offset_base, output_offset_base, requantize_multipliers_base, requantize_shifts_base, activation_min_base, activation_max_base, scratch_base, output_scratch_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[15]);


        }
    ),

    Kernel(
        "cortex_m::quantized_avg_pool2d.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 11, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)11, stack.size());
            EValue& input = *stack[0];
    	EValue& kernel_size = *stack[1];
    	EValue& stride = *stack[2];
    	EValue& padding = *stack[3];
    	EValue& ceil_mode = *stack[4];
    	EValue& zero_point = *stack[5];
    	EValue& multiplier = *stack[6];
    	EValue& shift = *stack[7];
    	EValue& scratch = *stack[8];
    	EValue& out = *stack[9];
    	const torch::executor::Tensor & input_base = input.to<torch::executor::Tensor>();

    	    auto kernel_size_list_out = kernel_size.toIntList();


    	    auto stride_list_out = stride.toIntList();


    	    auto padding_list_out = padding.toIntList();

    	bool ceil_mode_base = ceil_mode.to<bool>();
    	int64_t zero_point_base = zero_point.to<int64_t>();
    	int64_t multiplier_base = multiplier.to<int64_t>();
    	int64_t shift_base = shift.to<int64_t>();
    	const torch::executor::Tensor & scratch_base = scratch.to<torch::executor::Tensor>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_quantized_avg_pool2d.out");
            EXECUTORCH_SCOPE_PROF("native_call_quantized_avg_pool2d.out");
            cortex_m::native::quantized_avg_pool2d_out(context, input_base, kernel_size_list_out, stride_list_out, padding_list_out, ceil_mode_base, zero_point_base, multiplier_base, shift_base, scratch_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[9]);


        }
    ),

    Kernel(
        "cortex_m::quantized_max_pool2d.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 12, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)12, stack.size());
            EValue& input = *stack[0];
    	EValue& kernel_size = *stack[1];
    	EValue& stride = *stack[2];
    	EValue& padding = *stack[3];
    	EValue& dilation = *stack[4];
    	EValue& ceil_mode = *stack[5];
    	EValue& input_zero_point = *stack[6];
    	EValue& output_zero_point = *stack[7];
    	EValue& activation_min = *stack[8];
    	EValue& activation_max = *stack[9];
    	EValue& out = *stack[10];
    	const torch::executor::Tensor & input_base = input.to<torch::executor::Tensor>();

    	    auto kernel_size_list_out = kernel_size.toIntList();


    	    auto stride_list_out = stride.toIntList();


    	    auto padding_list_out = padding.toIntList();


    	    auto dilation_list_out = dilation.toIntList();

    	bool ceil_mode_base = ceil_mode.to<bool>();
    	int64_t input_zero_point_base = input_zero_point.to<int64_t>();
    	int64_t output_zero_point_base = output_zero_point.to<int64_t>();
    	int64_t activation_min_base = activation_min.to<int64_t>();
    	int64_t activation_max_base = activation_max.to<int64_t>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_quantized_max_pool2d.out");
            EXECUTORCH_SCOPE_PROF("native_call_quantized_max_pool2d.out");
            cortex_m::native::quantized_max_pool2d_out(context, input_base, kernel_size_list_out, stride_list_out, padding_list_out, dilation_list_out, ceil_mode_base, input_zero_point_base, output_zero_point_base, activation_min_base, activation_max_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[10]);


        }
    ),

    Kernel(
        "cortex_m::quantized_batch_matmul.out",
        [](torch::executor::KernelRuntimeContext & context, Span<EValue*> stack) {
            ET_KERNEL_CHECK_MSG(context, stack.size() == 10, InvalidProgram, /*void*/, "Expected %" ET_PRIsize_t "args received %" ET_PRIsize_t, (size_t)10, stack.size());
            EValue& lhs = *stack[0];
    	EValue& lhs_zero_point = *stack[1];
    	EValue& rhs_transposed = *stack[2];
    	EValue& rhs_zero_point = *stack[3];
    	EValue& output_zero_point = *stack[4];
    	EValue& output_multiplier = *stack[5];
    	EValue& output_shift = *stack[6];
    	EValue& scratch = *stack[7];
    	EValue& out = *stack[8];
    	const torch::executor::Tensor & lhs_base = lhs.to<torch::executor::Tensor>();
    	int64_t lhs_zero_point_base = lhs_zero_point.to<int64_t>();
    	const torch::executor::Tensor & rhs_transposed_base = rhs_transposed.to<torch::executor::Tensor>();
    	int64_t rhs_zero_point_base = rhs_zero_point.to<int64_t>();
    	int64_t output_zero_point_base = output_zero_point.to<int64_t>();
    	int64_t output_multiplier_base = output_multiplier.to<int64_t>();
    	int64_t output_shift_base = output_shift.to<int64_t>();
    	const torch::executor::Tensor & scratch_base = scratch.to<torch::executor::Tensor>();
    	torch::executor::Tensor & out_base = out.to<torch::executor::Tensor>();


            internal::EventTracerProfileOpScope event_tracer_op_scope(context.internal_event_tracer(), "native_call_quantized_batch_matmul.out");
            EXECUTORCH_SCOPE_PROF("native_call_quantized_batch_matmul.out");
            cortex_m::native::quantized_batch_matmul_out(context, lhs_base, lhs_zero_point_base, rhs_transposed_base, rhs_zero_point_base, output_zero_point_base, output_multiplier_base, output_shift_base, scratch_base, out_base);

            internal::event_tracer_log_evalue(context.internal_event_tracer(), *stack[8]);


        }
    ), // Generated kernels
};

// Explicitly convert to Span, so that the API can take an empty C array of
// Kernels.
static KernelSpan kernel_span(
    kernels_to_register,
    kernels_to_register + sizeof(kernels_to_register) / sizeof(Kernel));

// Return value not used. Keep the static variable assignment to register
// kernels in static initialization time.
static auto success_with_kernel_reg = register_kernels(kernel_span);
} // namespace
} // namespace function
} // namespace executor
} // namespace torch
